import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from './Components/HomeComponents/Navbar'
import Footer from './Components/HomeComponents/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Explore,Experience - Nomad',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     <div>
<Navbar/>
{children}
<Footer/>
        </div>
  )
}
